version: "3.7"
services:
  flask_app_gunicorn:
    init: true
    build: 
      context: ../flask_app
      dockerfile: Dockerfile-gunicorn
    environment: 
      - PORT_APP=3000
      - PORT_API=4000
      - WORKERS=1
      - THREADS=50
      - NUM_REQUESTS=10
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - slow_api

  slow_api:
    init: true
    build: ../slow_api
    environment: 
      - PORT=4000
    expose:
      - "4000"

