FROM python:3.8

RUN pip install Flask grequests gunicorn gevent numpy

COPY app.py /app.py
COPY patched.py /patched.py

CMD gunicorn --worker-class gevent \
  --workers $WORKERS \
  --bind 0.0.0.0:$PORT_APP \ 
  patched:app

