FROM python:3.8

RUN pip install 'fastapi[all]' 'uvicorn[standard]' 'gunicorn' 'aiohttp' 'numpy'

COPY app.py /app.py

CMD gunicorn  -w ${WORKERS} -k uvicorn.workers.UvicornWorker --bind "0.0.0.0:${PORT_APP}" 'app:app'
