# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_app/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_app/service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16grpc_app/service.proto\"\x1d\n\x0cMyAppRequest\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x05\"\x1d\n\rMyAppResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2b\n\x05MyApp\x12+\n\x08io_bound\x12\r.MyAppRequest\x1a\x0e.MyAppResponse\"\x00\x12,\n\tcpu_bound\x12\r.MyAppRequest\x1a\x0e.MyAppResponse\"\x00\x62\x06proto3'
)




_MYAPPREQUEST = _descriptor.Descriptor(
  name='MyAppRequest',
  full_name='MyAppRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='MyAppRequest.delay', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=55,
)


_MYAPPRESPONSE = _descriptor.Descriptor(
  name='MyAppResponse',
  full_name='MyAppResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='MyAppResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['MyAppRequest'] = _MYAPPREQUEST
DESCRIPTOR.message_types_by_name['MyAppResponse'] = _MYAPPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyAppRequest = _reflection.GeneratedProtocolMessageType('MyAppRequest', (_message.Message,), {
  'DESCRIPTOR' : _MYAPPREQUEST,
  '__module__' : 'grpc_app.service_pb2'
  # @@protoc_insertion_point(class_scope:MyAppRequest)
  })
_sym_db.RegisterMessage(MyAppRequest)

MyAppResponse = _reflection.GeneratedProtocolMessageType('MyAppResponse', (_message.Message,), {
  'DESCRIPTOR' : _MYAPPRESPONSE,
  '__module__' : 'grpc_app.service_pb2'
  # @@protoc_insertion_point(class_scope:MyAppResponse)
  })
_sym_db.RegisterMessage(MyAppResponse)



_MYAPP = _descriptor.ServiceDescriptor(
  name='MyApp',
  full_name='MyApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=88,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='io_bound',
    full_name='MyApp.io_bound',
    index=0,
    containing_service=None,
    input_type=_MYAPPREQUEST,
    output_type=_MYAPPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='cpu_bound',
    full_name='MyApp.cpu_bound',
    index=1,
    containing_service=None,
    input_type=_MYAPPREQUEST,
    output_type=_MYAPPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYAPP)

DESCRIPTOR.services_by_name['MyApp'] = _MYAPP

# @@protoc_insertion_point(module_scope)
